![alt text](Q5.png)

In [2]:
# Discrete Functions are dating with numpy ****
import numpy as np

# Firstly lets replicate the functions 
n = np.arange(-7,7)
#Create the corresponding y values
x = np.array([0, 0, 0, -1, -1, -1, 0, 1, 2, 3, 3,1, 1, 0])

h = np.array([0, 0, 0, 0, 0, 0, 0, 0 ,0 ,2, 3, 1, 0, 0])
print(n)
print(x)
print(h)

[-7 -6 -5 -4 -3 -2 -1  0  1  2  3  4  5  6]
[ 0  0  0 -1 -1 -1  0  1  2  3  3  1  1  0]
[0 0 0 0 0 0 0 0 0 2 3 1 0 0]


In [10]:
y = np.convolve(h,x,mode = "valid")
print(f'y[-1] = {y[-1]}')

y[-1] = -5
