![alt text](Q5.png)

In [9]:
# Discrete Functions are dating with numpy ****
import numpy as np
# Firstly lets replicate the functions 
n = np.arange(-5,7)
#Create the corrspnding y values
x = np.array([0, 0, 0, -1, -1, -1, 0, 1, 2, 3, 3,1, 1, 0])
h = np.array([ 0, 0, 0, 0, 0 ,0 ,2, 3, 1, 0, 0])
print(n)
print(x)
print(h)

[-5 -4 -3 -2 -1  0  1  2  3  4  5  6]
[ 0  0  0 -1 -1 -1  0  1  2  3  3  1  1  0]
[0 0 0 0 0 0 2 3 1 0 0]


In [25]:
y = np.convolve(h,x,mode = "same")
print(n)
print(x)
print(h)
print(y)


[-5 -4 -3 -2 -1  0  1  2  3  4  5  6]
[ 0  0  0 -1 -1 -1  0  1  2  3  3  1  1  0]
[0 0 0 0 0 0 2 3 1 0 0]
[ 0  0  0  0 -2 -5 -6 -4  1  7 13 17 14  8]
